name: Build pages

on:
  push:
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install packages
        run: pip install .

      - name: Run script
        run: python src/lates.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docs'
          message: 'docs: rebuilt github pages'
